### ISSUE TITLE
changelog/migration guide missing information about statsd.connection going away

### ISSUE THREAD

**Issue by erikbelusic** [DataDog/dogstatsd-ruby#270]
In the section for 4.x.x breaking change (https://github.com/DataDog/dogstatsd-ruby/blob/master/CHANGELOG.md#breaking-changes)

> port / host / socket_path readers are now on `statsd.connection`

When i upgraded to 5 - it looks like these are back on the `statsd` instance - but I didn't see this change listed in the changed log

**Comment by remeh** [comment]
Hey @erikbelusic, thanks for having opened an issue.
Can you confirm that you were running a version 4.x < to `4.9.0` before migrating to `5.x.x`? I'll update the CHANGELOG but I think `port / host / socket_path` were re-introduced in the `statsd` object in version `4.9.0`.

**Comment by erikbelusic** [comment]
Yup.

We were initially on `3.3.0`. We then went `3.3.0` -> `4.8.3` (because 4.9.x was yanked) and followed up with `4.8.3` -> `5.5.0`


Assume `$statsd` is our global client.

when going from `3.3.0` -> `4.8.3` we made a change like:
```
@alternate_client ||=
      Datadog::Statsd.new($statsd.host, $statsd.port, namespace: $statsd.namespace, tags: ["other:tags"])
```
to
```
@alternate_client ||=
      Datadog::Statsd.new($statsd.connection.host, $statsd.connection.port, namespace: $statsd.namespace, tags: ["other:tags"])
```

When going from `4.8.3` -> `5.5.0` we encountered
```
NoMethodError:
--
  | undefined method `connection' for #<Datadog::Statsd:0x000055ac26481c78 ... >

```
and had to revert this change. I believe this was a breaking change that was missing from the change log (unless i missed it)

If `4.9.x` was yanked, this note likely makes the most sense in the `5.0.0` change log entry

**Comment by remeh** [comment]
Ha you're right I forgot about 4.9.0 being yanked. #273 should address your concern, please let me know.

**Comment by remeh** [comment]
Closing this. Thanks again for your report @erikbelusic 👍
