### ISSUE TITLE
Tags cannot be symbols since 2.0.0

### ISSUE THREAD

**Issue by viraptor** [DataDog/dogstatsd-ruby#50]
This is a late bug, but when updating from 1.6.0, we noticed that symbols can't be used in tags anymore.

2.0.0 started running `gsub` on them, resulting in
```
undefined method `gsub' for :.....:Symbol
```
and 3.0.0 fails with `TypeError: can't dup Symbol`

I understand if this could be a new, expected behaviour. (in that case you may want to update the breaking changes list)
